# Generated by Django 2.2 on 2021-03-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
    ]
