# Generated by Django 2.2 on 2021-03-02 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0003_auto_20210302_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
