# Generated by Django 2.2 on 2021-03-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0004_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
