# Generated by Django 2.2 on 2021-03-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0005_auto_20210302_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(db_index=True, max_length=200, verbose_name='Описание продукта'),
        ),
    ]
