# Generated by Django 2.2 on 2021-03-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0006_auto_20210303_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
