# Generated by Django 2.2 on 2021-03-02 21:11

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0007_auto_20210303_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=builtins.id, max_length=100, unique=True),
        ),
    ]
