# Generated by Django 2.2 on 2021-03-03 17:43

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0008_auto_20210303_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(default=builtins.id, max_length=100, unique=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
