# Generated by Django 2.2 on 2021-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
